const moduleKeys = {
  HOSPITALITY_RECORDS: "HOSPITALITY_RECORDS",
  PURCHASE_RECORDS: "PURCHASE_RECORDS",
  USAGE_RECORDS: "USAGE_RECORDS",
  INVOICE_CONFLICT: "INVOICE_CONFLICT",
  COUNTERPARTY: "COUNTERPARTY",
  USERS: "USERS",
  DEPARTMENT: "DEPARTMENT",
  POSITION: "POSITION",
  GRADE: "GRADE",
  PER_CAPITA_LIMIT: "PER_CAPITA_LIMIT",
};
export default moduleKeys;
