const moduleKeys = {
  HOSPITALITY_RECORDS: "HOSPITALITY_RECORDS",
  PURCHASE_RECORDS: "PURCHASE_RECORDS",
  USAGE_RECORDS: "USAGE_RECORDS",
  INVOICE_CONFLICT: "INVOICE_CONFLICT",
  COUNTERPARTY: "COUNTERPARTY",
  DEPARTMENT: "DEPARTMENT",
  POSITION: "POSITION",
  GRADE: "GRADE",
};
export default moduleKeys;
